// Cloned from https://example.com (public domain, IANA) — structure + text only.
// Generated by website-cloner-uiux agent (Phase 2 M7, limited).
// - Pure React + Tailwind (Vite-compatible). NO Next.js.
// - No copyrighted images/assets copied; text reproduced per IANA permission.
export default function ExampleClone() {
  return (
    <div className="min-h-screen w-full bg-white text-gray-900 flex flex-col">
      <main className="flex-1 flex flex-col items-center justify-center px-6 py-16 text-center">
        <h1 className="text-4xl font-bold tracking-tight text-gray-900 mb-6">
          Example Domain
        </h1>
        <p className="text-base leading-relaxed text-gray-600 max-w-xl mb-4">
          This domain is for use in documentation examples without needing permission. Avoid use in operations.
        </p>
        <a
          href="https://iana.org/domains/example"
          className="text-blue-600 hover:text-blue-800 hover:underline transition-colors"
        >
          Learn more
        </a>
      </main>
    </div>
  );
}
